// <auto-generated />
using System;
using HrisApp.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HrisApp.Server.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20231113011810_i")]
    partial class i
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("HrisApp.Shared.Models.Education.CollegeT", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("CollAward")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CollCourse")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CollSchoolLoc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CollSchoolName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CollSchoolYear")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Verify_Id")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CollegeT");
                });

            modelBuilder.Entity("HrisApp.Shared.Models.Education.DoctorateT", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("DocAward")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DocCourse")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DocSchoolLoc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DocSchoolName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DocSchoolYear")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Verify_Id")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DoctorateT");
                });

            modelBuilder.Entity("HrisApp.Shared.Models.Education.MasteralT", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("MasAward")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MasCourse")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MasSchoolLoc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MasSchoolName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MasSchoolYear")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Verify_Id")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("MasteralT");
                });

            modelBuilder.Entity("HrisApp.Shared.Models.Education.OtherEducT", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("OthersAward")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OthersCourse")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OthersSchoolLoc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OthersSchoolName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OthersSchoolType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OthersSchoolYear")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Verify_Id")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("OtherEducT");
                });

            modelBuilder.Entity("HrisApp.Shared.Models.Education.PrimaryT", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("PriAward")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PriSchoolLoc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PriSchoolName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PriSchoolYear")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Verify_Id")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PrimaryT");
                });

            modelBuilder.Entity("HrisApp.Shared.Models.Education.SecondaryT", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("SecAward")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecSchoolLoc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecSchoolName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecSchoolYear")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Verify_Id")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SecondaryT");
                });

            modelBuilder.Entity("HrisApp.Shared.Models.Education.SeniorHST", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ShsAward")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShsSchoolLoc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShsSchoolName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShsSchoolYear")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Verify_Id")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SeniorHST");
                });

            modelBuilder.Entity("HrisApp.Shared.Models.Employee.AddressT", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("CurrentAdd")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CurrentBrgy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CurrentCity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CurrentCountry")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CurrentProvince")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CurrentZipCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PermanentAdd")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PermanentBrgy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PermanentCity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PermanentCountry")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PermanentProvince")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PermanentZipCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Verify_Id")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AddressT");
                });

            modelBuilder.Entity("HrisApp.Shared.Models.Employee.CivilStatusT", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CivilStatusT");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Single"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Married"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Widowed"
                        });
                });

            modelBuilder.Entity("HrisApp.Shared.Models.Employee.EmerRelationshipT", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("EmerRelationshipT");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Mother"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Father"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Spouse"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Sibling"
                        });
                });

            modelBuilder.Entity("HrisApp.Shared.Models.Employee.EmployeeT", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<int>("AreaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Birthdate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CivilStatusId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateHired")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateInactiveStatus")
                        .HasColumnType("datetime2");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<int>("DivisionId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmerAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmerMobNum")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EmerRelationshipId")
                        .HasColumnType("int");

                    b.Property<string>("EmployeeNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EmploymentStatusId")
                        .HasColumnType("int");

                    b.Property<string>("Extension")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GenderId")
                        .HasColumnType("int");

                    b.Property<int?>("Height")
                        .HasColumnType("int");

                    b.Property<int>("InactiveStatusId")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MiddleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MobileNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nationality")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PositionId")
                        .HasColumnType("int");

                    b.Property<int>("ReligionId")
                        .HasColumnType("int");

                    b.Property<int>("SectionId")
                        .HasColumnType("int");

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.Property<string>("Verify_Id")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Weight")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AreaId");

                    b.HasIndex("CivilStatusId");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("DivisionId");

                    b.HasIndex("EmerRelationshipId");

                    b.HasIndex("EmploymentStatusId");

                    b.HasIndex("GenderId");

                    b.HasIndex("InactiveStatusId");

                    b.HasIndex("PositionId");

                    b.HasIndex("ReligionId");

                    b.HasIndex("StatusId");

                    b.ToTable("EmployeeT");
                });

            modelBuilder.Entity("HrisApp.Shared.Models.Employee.EmploymentDateT", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime?>("CasualEndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("CasualStartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("EmpmentStatusId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FixedEndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FixedStartDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ProbationEndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ProbationStartDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ProjEndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ProjStartDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("RegularizationDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ResignationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Verify_Id")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("EmploymentDateT");
                });

            modelBuilder.Entity("HrisApp.Shared.Models.Employee.EmploymentStatusT", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("EmploymentStatusT");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Regular"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Probationary"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Casual"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Fixed Term"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Project Based"
                        });
                });

            modelBuilder.Entity("HrisApp.Shared.Models.Employee.GenderT", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("GenderT");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Male"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Female"
                        });
                });

            modelBuilder.Entity("HrisApp.Shared.Models.Employee.InactiveStatusT", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("InactiveStatusT");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Active"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Resigned"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Terminated"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Awol"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Retired"
                        });
                });

            modelBuilder.Entity("HrisApp.Shared.Models.Employee.ReligionT", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ReligionT");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Roman Catholic"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Iglesia ni Cristo"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Evangelicals (PCEC)"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Non-Roman Catholic"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Protestant (NCCP)"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Aglipayan"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Seventh-day Adventist"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Bible Baptist Church"
                        },
                        new
                        {
                            Id = 9,
                            Name = "United Church of Christ in the Philippines"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Jehovah's Witnesses"
                        },
                        new
                        {
                            Id = 11,
                            Name = "None"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Others"
                        });
                });

            modelBuilder.Entity("HrisApp.Shared.Models.Employee.StatusT", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("StatusT");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Active"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Inactive"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Resigned"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Terminated"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Awol"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Retired"
                        });
                });

            modelBuilder.Entity("HrisApp.Shared.Models.Images.DocumentT", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<int>("DivisionId")
                        .HasColumnType("int");

                    b.Property<string>("EmployeeNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Img_Contenttype")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("Img_Data")
                        .HasColumnType("varbinary(max)");

                    b.Property<DateTime>("Img_Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Img_Filename")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Img_URL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Verify_Id")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("DivisionId");

                    b.ToTable("DocumentT");
                });

            modelBuilder.Entity("HrisApp.Shared.Models.Images.EmpPictureT", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<int>("DivisionId")
                        .HasColumnType("int");

                    b.Property<string>("EmployeeNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Img_Contenttype")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("Img_Data")
                        .HasColumnType("varbinary(max)");

                    b.Property<DateTime>("Img_Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Img_Filename")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Img_URL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Verify_Id")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("DivisionId");

                    b.ToTable("EmpPictureT");
                });

            modelBuilder.Entity("HrisApp.Shared.Models.LiscenseAndTraining.LicenseT", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime?>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Examination")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LicenseNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rating")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Verify_Id")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("LicenseT");
                });

            modelBuilder.Entity("HrisApp.Shared.Models.LiscenseAndTraining.TrainingT", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("SponsorSpeaker")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("TrainingDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("TrainingName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Verify_Id")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TrainingT");
                });

            modelBuilder.Entity("HrisApp.Shared.Models.MasterData.AreaT", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AreaT");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Davao"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Digos"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Kidapawan"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Cotabato"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Calinan"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Gumalang"
                        });
                });

            modelBuilder.Entity("HrisApp.Shared.Models.MasterData.DepartmentT", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("DivisionId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DepartmentT");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DivisionId = 1,
                            Name = "Sonic 1"
                        },
                        new
                        {
                            Id = 2,
                            DivisionId = 1,
                            Name = "Sonic 2"
                        },
                        new
                        {
                            Id = 3,
                            DivisionId = 1,
                            Name = "Sonic 3 Digos"
                        },
                        new
                        {
                            Id = 4,
                            DivisionId = 1,
                            Name = "Sonic 3 Kidapawan"
                        },
                        new
                        {
                            Id = 5,
                            DivisionId = 1,
                            Name = "Sonic 3 Cotabato"
                        },
                        new
                        {
                            Id = 6,
                            DivisionId = 1,
                            Name = "URIC"
                        },
                        new
                        {
                            Id = 7,
                            DivisionId = 1,
                            Name = "UFS"
                        },
                        new
                        {
                            Id = 8,
                            DivisionId = 1,
                            Name = "GCash"
                        },
                        new
                        {
                            Id = 9,
                            DivisionId = 2,
                            Name = "General Accounting"
                        },
                        new
                        {
                            Id = 10,
                            DivisionId = 2,
                            Name = "Sales Accounting"
                        },
                        new
                        {
                            Id = 11,
                            DivisionId = 2,
                            Name = "Information Technology"
                        },
                        new
                        {
                            Id = 12,
                            DivisionId = 2,
                            Name = "Treasury"
                        },
                        new
                        {
                            Id = 16,
                            DivisionId = 3,
                            Name = "Warehouse"
                        },
                        new
                        {
                            Id = 17,
                            DivisionId = 3,
                            Name = "Transport"
                        },
                        new
                        {
                            Id = 18,
                            DivisionId = 3,
                            Name = "Inventory Planning and Principal Relations"
                        },
                        new
                        {
                            Id = 19,
                            DivisionId = 3,
                            Name = "Order Processing"
                        },
                        new
                        {
                            Id = 20,
                            DivisionId = 3,
                            Name = "Logistics"
                        },
                        new
                        {
                            Id = 21,
                            DivisionId = 4,
                            Name = "Human Resource"
                        },
                        new
                        {
                            Id = 22,
                            DivisionId = 4,
                            Name = "General Services"
                        },
                        new
                        {
                            Id = 23,
                            DivisionId = 5,
                            Name = "Canaan"
                        },
                        new
                        {
                            Id = 24,
                            DivisionId = 5,
                            Name = "RTL"
                        },
                        new
                        {
                            Id = 25,
                            DivisionId = 5,
                            Name = "Pullet"
                        });
                });

            modelBuilder.Entity("HrisApp.Shared.Models.MasterData.DivisionT", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DivisionT");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Sales Operations"
                        },
                        new
                        {
                            Id = 2,
                            Name = "FAMS"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Supply Chain Management Service"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Central Administration"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Agro Industrial"
                        });
                });

            modelBuilder.Entity("HrisApp.Shared.Models.MasterData.PositionT", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<int>("DivisionId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Plantilla")
                        .HasColumnType("int");

                    b.Property<string>("PosCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SectionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("PositionT");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DepartmentId = 1,
                            DivisionId = 1,
                            Name = "FSS",
                            Plantilla = 1,
                            PosCode = "S101",
                            SectionId = 0
                        },
                        new
                        {
                            Id = 2,
                            DepartmentId = 1,
                            DivisionId = 1,
                            Name = "Feeder",
                            Plantilla = 9,
                            PosCode = "S102",
                            SectionId = 0
                        },
                        new
                        {
                            Id = 3,
                            DepartmentId = 1,
                            DivisionId = 1,
                            Name = "FCCR",
                            Plantilla = 2,
                            PosCode = "S103",
                            SectionId = 0
                        },
                        new
                        {
                            Id = 4,
                            DepartmentId = 4,
                            DivisionId = 1,
                            Name = "FSS",
                            Plantilla = 1,
                            PosCode = "S3K01",
                            SectionId = 0
                        },
                        new
                        {
                            Id = 5,
                            DepartmentId = 4,
                            DivisionId = 1,
                            Name = "DT Booking/ GT Booking",
                            Plantilla = 1,
                            PosCode = "S3K02",
                            SectionId = 0
                        },
                        new
                        {
                            Id = 6,
                            DepartmentId = 4,
                            DivisionId = 1,
                            Name = "DSS",
                            Plantilla = 1,
                            PosCode = "S3K03",
                            SectionId = 0
                        },
                        new
                        {
                            Id = 7,
                            DepartmentId = 4,
                            DivisionId = 1,
                            Name = "PM Salesman",
                            Plantilla = 1,
                            PosCode = "S3K04",
                            SectionId = 0
                        },
                        new
                        {
                            Id = 8,
                            DepartmentId = 4,
                            DivisionId = 1,
                            Name = "OMNI Feeder",
                            Plantilla = 3,
                            PosCode = "S3K05",
                            SectionId = 0
                        },
                        new
                        {
                            Id = 9,
                            DepartmentId = 4,
                            DivisionId = 1,
                            Name = "FCCR",
                            Plantilla = 1,
                            PosCode = "S3K06",
                            SectionId = 0
                        },
                        new
                        {
                            Id = 10,
                            DepartmentId = 5,
                            DivisionId = 1,
                            Name = "FSS",
                            Plantilla = 1,
                            PosCode = "S3C01",
                            SectionId = 0
                        },
                        new
                        {
                            Id = 11,
                            DepartmentId = 5,
                            DivisionId = 1,
                            Name = "DT Booking/ GT Booking",
                            Plantilla = 2,
                            PosCode = "S3C02",
                            SectionId = 0
                        },
                        new
                        {
                            Id = 12,
                            DepartmentId = 5,
                            DivisionId = 1,
                            Name = "DSS",
                            Plantilla = 1,
                            PosCode = "S3C03",
                            SectionId = 0
                        },
                        new
                        {
                            Id = 13,
                            DepartmentId = 5,
                            DivisionId = 1,
                            Name = "OMNI Feeder",
                            Plantilla = 3,
                            PosCode = "S3C04",
                            SectionId = 0
                        },
                        new
                        {
                            Id = 14,
                            DepartmentId = 5,
                            DivisionId = 1,
                            Name = "FCCR",
                            Plantilla = 1,
                            PosCode = "S3C05",
                            SectionId = 0
                        },
                        new
                        {
                            Id = 15,
                            DepartmentId = 6,
                            DivisionId = 1,
                            Name = "Operations Manager",
                            Plantilla = 1,
                            PosCode = "URIC01",
                            SectionId = 0
                        },
                        new
                        {
                            Id = 16,
                            DepartmentId = 6,
                            DivisionId = 1,
                            Name = "HAPI Supervisor",
                            Plantilla = 1,
                            PosCode = "URICHAP01",
                            SectionId = 4
                        },
                        new
                        {
                            Id = 17,
                            DepartmentId = 6,
                            DivisionId = 1,
                            Name = "HAPI Dealer Coor",
                            Plantilla = 4,
                            PosCode = "URICHAP02",
                            SectionId = 4
                        },
                        new
                        {
                            Id = 18,
                            DepartmentId = 6,
                            DivisionId = 1,
                            Name = "Field Sales Supervisor",
                            Plantilla = 1,
                            PosCode = "URICSER01",
                            SectionId = 5
                        },
                        new
                        {
                            Id = 19,
                            DepartmentId = 6,
                            DivisionId = 1,
                            Name = "MAG Supervisor",
                            Plantilla = 1,
                            PosCode = "URICSER02",
                            SectionId = 5
                        },
                        new
                        {
                            Id = 20,
                            DepartmentId = 6,
                            DivisionId = 1,
                            Name = "GTAS",
                            Plantilla = 5,
                            PosCode = "URICSER03",
                            SectionId = 5
                        },
                        new
                        {
                            Id = 21,
                            DepartmentId = 6,
                            DivisionId = 1,
                            Name = "SMS",
                            Plantilla = 11,
                            PosCode = "URICSER04",
                            SectionId = 5
                        },
                        new
                        {
                            Id = 22,
                            DepartmentId = 6,
                            DivisionId = 1,
                            Name = "NAO Supervisor",
                            Plantilla = 1,
                            PosCode = "URICEXP01",
                            SectionId = 6
                        },
                        new
                        {
                            Id = 23,
                            DepartmentId = 6,
                            DivisionId = 1,
                            Name = "NAO",
                            Plantilla = 2,
                            PosCode = "URICEXP02",
                            SectionId = 6
                        },
                        new
                        {
                            Id = 24,
                            DepartmentId = 6,
                            DivisionId = 1,
                            Name = "HAPI NAO",
                            Plantilla = 4,
                            PosCode = "URICEXP02",
                            SectionId = 6
                        },
                        new
                        {
                            Id = 25,
                            DepartmentId = 6,
                            DivisionId = 1,
                            Name = "IT & Support Services Staff",
                            Plantilla = 1,
                            PosCode = "URICDTE01",
                            SectionId = 7
                        },
                        new
                        {
                            Id = 26,
                            DepartmentId = 6,
                            DivisionId = 1,
                            Name = "Teleservices Support Staff / Online Coor",
                            Plantilla = 1,
                            PosCode = "URICDTE02",
                            SectionId = 7
                        },
                        new
                        {
                            Id = 27,
                            DepartmentId = 8,
                            DivisionId = 1,
                            Name = "Field Sales Manager",
                            Plantilla = 1,
                            PosCode = "GCASH01",
                            SectionId = 0
                        },
                        new
                        {
                            Id = 28,
                            DepartmentId = 8,
                            DivisionId = 1,
                            Name = "Field Sales Supervisor",
                            Plantilla = 1,
                            PosCode = "GCASH02",
                            SectionId = 0
                        },
                        new
                        {
                            Id = 29,
                            DepartmentId = 8,
                            DivisionId = 1,
                            Name = "Field Sales Supervisor",
                            Plantilla = 1,
                            PosCode = "GCASHSER01",
                            SectionId = 8
                        },
                        new
                        {
                            Id = 30,
                            DepartmentId = 8,
                            DivisionId = 1,
                            Name = "Sonic DSP",
                            Plantilla = 4,
                            PosCode = "GCASHSER02",
                            SectionId = 8
                        },
                        new
                        {
                            Id = 31,
                            DepartmentId = 8,
                            DivisionId = 1,
                            Name = "DSP (Commando/Incubator)",
                            Plantilla = 6,
                            PosCode = "GCASHSER03",
                            SectionId = 8
                        },
                        new
                        {
                            Id = 32,
                            DepartmentId = 8,
                            DivisionId = 1,
                            Name = "Ambassador",
                            Plantilla = 2,
                            PosCode = "GCASHEXP01",
                            SectionId = 9
                        },
                        new
                        {
                            Id = 33,
                            DepartmentId = 8,
                            DivisionId = 1,
                            Name = "Merchandiser",
                            Plantilla = 3,
                            PosCode = "GCASHMER01",
                            SectionId = 10
                        },
                        new
                        {
                            Id = 34,
                            DepartmentId = 8,
                            DivisionId = 1,
                            Name = "Scan to Pay",
                            Plantilla = 3,
                            PosCode = "GCASHSCA01",
                            SectionId = 11
                        },
                        new
                        {
                            Id = 35,
                            DepartmentId = 9,
                            DivisionId = 2,
                            Name = "Team Leader/Supervisor",
                            Plantilla = 1,
                            PosCode = "GAINV01",
                            SectionId = 12
                        },
                        new
                        {
                            Id = 36,
                            DepartmentId = 9,
                            DivisionId = 2,
                            Name = "Trade Payable Staff",
                            Plantilla = 2,
                            PosCode = "GAINV02",
                            SectionId = 12
                        },
                        new
                        {
                            Id = 37,
                            DepartmentId = 9,
                            DivisionId = 2,
                            Name = "Non Trade Payable Staff",
                            Plantilla = 1,
                            PosCode = "GAINV03",
                            SectionId = 12
                        },
                        new
                        {
                            Id = 38,
                            DepartmentId = 9,
                            DivisionId = 2,
                            Name = "Team Leader/Supervisor",
                            Plantilla = 1,
                            PosCode = "GAGEN01",
                            SectionId = 13
                        },
                        new
                        {
                            Id = 39,
                            DepartmentId = 9,
                            DivisionId = 2,
                            Name = "Gen Accounting Staff",
                            Plantilla = 3,
                            PosCode = "GAGEN02",
                            SectionId = 13
                        },
                        new
                        {
                            Id = 40,
                            DepartmentId = 9,
                            DivisionId = 2,
                            Name = "Team Leader/Supervisor",
                            Plantilla = 1,
                            PosCode = "GATAX01",
                            SectionId = 14
                        },
                        new
                        {
                            Id = 41,
                            DepartmentId = 9,
                            DivisionId = 2,
                            Name = "Tax and Compliance Staff",
                            Plantilla = 3,
                            PosCode = "GATAX02",
                            SectionId = 14
                        },
                        new
                        {
                            Id = 42,
                            DepartmentId = 10,
                            DivisionId = 2,
                            Name = "Team Leader",
                            Plantilla = 1,
                            PosCode = "SAACC01",
                            SectionId = 15
                        },
                        new
                        {
                            Id = 43,
                            DepartmentId = 10,
                            DivisionId = 2,
                            Name = "Accounts Receivable Staff",
                            Plantilla = 4,
                            PosCode = "SAACC02",
                            SectionId = 15
                        },
                        new
                        {
                            Id = 44,
                            DepartmentId = 10,
                            DivisionId = 2,
                            Name = "Credit and Collection Staff",
                            Plantilla = 6,
                            PosCode = "SACRE01",
                            SectionId = 16
                        },
                        new
                        {
                            Id = 45,
                            DepartmentId = 10,
                            DivisionId = 2,
                            Name = "C&C - Billings to Customer",
                            Plantilla = 1,
                            PosCode = "SACRE02",
                            SectionId = 16
                        },
                        new
                        {
                            Id = 46,
                            DepartmentId = 10,
                            DivisionId = 2,
                            Name = "Billing to Cash Settlement Staff",
                            Plantilla = 1,
                            PosCode = "SABIL01",
                            SectionId = 17
                        },
                        new
                        {
                            Id = 47,
                            DepartmentId = 11,
                            DivisionId = 2,
                            Name = "Manager",
                            Plantilla = 1,
                            PosCode = "IT01",
                            SectionId = 0
                        },
                        new
                        {
                            Id = 48,
                            DepartmentId = 11,
                            DivisionId = 2,
                            Name = "IT Associate",
                            Plantilla = 2,
                            PosCode = "IT02",
                            SectionId = 0
                        },
                        new
                        {
                            Id = 49,
                            DepartmentId = 11,
                            DivisionId = 2,
                            Name = "IT Staff",
                            Plantilla = 3,
                            PosCode = "IT03",
                            SectionId = 0
                        },
                        new
                        {
                            Id = 50,
                            DepartmentId = 12,
                            DivisionId = 2,
                            Name = "Cash Operations Head",
                            Plantilla = 1,
                            PosCode = "TREASURYCAS01",
                            SectionId = 18
                        },
                        new
                        {
                            Id = 51,
                            DepartmentId = 12,
                            DivisionId = 2,
                            Name = "Davao Cashier",
                            Plantilla = 3,
                            PosCode = "TREASURYCAS02",
                            SectionId = 18
                        },
                        new
                        {
                            Id = 52,
                            DepartmentId = 12,
                            DivisionId = 2,
                            Name = "Cotabato Cashier",
                            Plantilla = 1,
                            PosCode = "TREASURYCAS03",
                            SectionId = 18
                        },
                        new
                        {
                            Id = 53,
                            DepartmentId = 12,
                            DivisionId = 2,
                            Name = "Kidapawan Cashier",
                            Plantilla = 1,
                            PosCode = "TREASURYCAS04",
                            SectionId = 18
                        },
                        new
                        {
                            Id = 54,
                            DepartmentId = 12,
                            DivisionId = 2,
                            Name = "Digos Cashier",
                            Plantilla = 1,
                            PosCode = "TREASURYCAS05",
                            SectionId = 18
                        });
                });

            modelBuilder.Entity("HrisApp.Shared.Models.MasterData.SectionT", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<int>("DivisionId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SectionT");

                    b.HasData(
                        new
                        {
                            Id = 4,
                            DepartmentId = 6,
                            DivisionId = 1,
                            Name = "Hapi Dealer"
                        },
                        new
                        {
                            Id = 5,
                            DepartmentId = 6,
                            DivisionId = 1,
                            Name = "Servicing"
                        },
                        new
                        {
                            Id = 6,
                            DepartmentId = 6,
                            DivisionId = 1,
                            Name = "Expansion"
                        },
                        new
                        {
                            Id = 7,
                            DepartmentId = 6,
                            DivisionId = 1,
                            Name = "DTEX"
                        },
                        new
                        {
                            Id = 8,
                            DepartmentId = 8,
                            DivisionId = 1,
                            Name = "Servicing"
                        },
                        new
                        {
                            Id = 9,
                            DepartmentId = 8,
                            DivisionId = 1,
                            Name = "Expansion"
                        },
                        new
                        {
                            Id = 10,
                            DepartmentId = 8,
                            DivisionId = 1,
                            Name = "Merchandising"
                        },
                        new
                        {
                            Id = 11,
                            DepartmentId = 8,
                            DivisionId = 1,
                            Name = "Scan To Pay"
                        },
                        new
                        {
                            Id = 12,
                            DepartmentId = 9,
                            DivisionId = 1,
                            Name = "Inventory and Accnts. Payable"
                        },
                        new
                        {
                            Id = 13,
                            DepartmentId = 9,
                            DivisionId = 1,
                            Name = "General Accounting"
                        },
                        new
                        {
                            Id = 14,
                            DepartmentId = 9,
                            DivisionId = 1,
                            Name = "Tax and Compliance"
                        },
                        new
                        {
                            Id = 15,
                            DepartmentId = 10,
                            DivisionId = 1,
                            Name = "Accounts Receivable"
                        },
                        new
                        {
                            Id = 16,
                            DepartmentId = 10,
                            DivisionId = 1,
                            Name = "Credit and Collection"
                        },
                        new
                        {
                            Id = 17,
                            DepartmentId = 10,
                            DivisionId = 1,
                            Name = "Billing to Cash Settlement"
                        },
                        new
                        {
                            Id = 18,
                            DepartmentId = 12,
                            DivisionId = 1,
                            Name = "Cash Operations"
                        });
                });

            modelBuilder.Entity("HrisApp.Shared.Models.Payroll.CashBondT", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CashBondT");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Yes"
                        },
                        new
                        {
                            Id = 2,
                            Name = "No"
                        });
                });

            modelBuilder.Entity("HrisApp.Shared.Models.Payroll.PayrollT", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("BankAcc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BiometricID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CashbondId")
                        .HasColumnType("int");

                    b.Property<string>("HDMFNum")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MealAllowance")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Paytype")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhilHealthNum")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RateTypeId")
                        .HasColumnType("int");

                    b.Property<int>("RestDayId")
                        .HasColumnType("int");

                    b.Property<string>("SSSNum")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Salary")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ScheduleTypeId")
                        .HasColumnType("int");

                    b.Property<string>("TINNum")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Verify_Id")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CashbondId");

                    b.HasIndex("RateTypeId");

                    b.HasIndex("RestDayId");

                    b.HasIndex("ScheduleTypeId");

                    b.ToTable("PayrollT");
                });

            modelBuilder.Entity("HrisApp.Shared.Models.Payroll.RateTypeT", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("RateTypeT");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Monthly Rate"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Daily Rate"
                        });
                });

            modelBuilder.Entity("HrisApp.Shared.Models.Payroll.RestDayT", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("RestDayT");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Sunday"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Monday"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Tuesday"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Wednesday"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Thursday"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Friday"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Saturday"
                        });
                });

            modelBuilder.Entity("HrisApp.Shared.Models.Payroll.ScheduleTypeT", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TimeIn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TimeOut")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ScheduleTypeT");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Regular",
                            TimeIn = "08:00 AM",
                            TimeOut = "05:00 PM"
                        });
                });

            modelBuilder.Entity("HrisApp.Shared.Models.User.UserMasterT", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LoginStatus")
                        .HasColumnType("bit");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("PasswordHash")
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("PasswordSalt")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("ReferralCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("UserMasterT");
                });

            modelBuilder.Entity("HrisApp.Shared.Models.User.UserRoleT", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("UserRoleT");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Administrator",
                            RoleCode = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            Name = "User",
                            RoleCode = "User"
                        });
                });

            modelBuilder.Entity("HrisApp.Shared.Models.Employee.EmployeeT", b =>
                {
                    b.HasOne("HrisApp.Shared.Models.MasterData.AreaT", "Area")
                        .WithMany()
                        .HasForeignKey("AreaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HrisApp.Shared.Models.Employee.CivilStatusT", "CivilStatus")
                        .WithMany()
                        .HasForeignKey("CivilStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HrisApp.Shared.Models.MasterData.DepartmentT", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HrisApp.Shared.Models.MasterData.DivisionT", "Division")
                        .WithMany()
                        .HasForeignKey("DivisionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HrisApp.Shared.Models.Employee.EmerRelationshipT", "EmerRelationship")
                        .WithMany()
                        .HasForeignKey("EmerRelationshipId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HrisApp.Shared.Models.Employee.EmploymentStatusT", "EmploymentStatus")
                        .WithMany()
                        .HasForeignKey("EmploymentStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HrisApp.Shared.Models.Employee.GenderT", "Gender")
                        .WithMany()
                        .HasForeignKey("GenderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HrisApp.Shared.Models.Employee.InactiveStatusT", "InactiveStatus")
                        .WithMany()
                        .HasForeignKey("InactiveStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HrisApp.Shared.Models.MasterData.PositionT", "Position")
                        .WithMany()
                        .HasForeignKey("PositionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HrisApp.Shared.Models.Employee.ReligionT", "Religion")
                        .WithMany()
                        .HasForeignKey("ReligionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HrisApp.Shared.Models.Employee.StatusT", "Status")
                        .WithMany()
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Area");

                    b.Navigation("CivilStatus");

                    b.Navigation("Department");

                    b.Navigation("Division");

                    b.Navigation("EmerRelationship");

                    b.Navigation("EmploymentStatus");

                    b.Navigation("Gender");

                    b.Navigation("InactiveStatus");

                    b.Navigation("Position");

                    b.Navigation("Religion");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("HrisApp.Shared.Models.Images.DocumentT", b =>
                {
                    b.HasOne("HrisApp.Shared.Models.MasterData.DepartmentT", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HrisApp.Shared.Models.MasterData.DivisionT", "Division")
                        .WithMany()
                        .HasForeignKey("DivisionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("Division");
                });

            modelBuilder.Entity("HrisApp.Shared.Models.Images.EmpPictureT", b =>
                {
                    b.HasOne("HrisApp.Shared.Models.MasterData.DepartmentT", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HrisApp.Shared.Models.MasterData.DivisionT", "Division")
                        .WithMany()
                        .HasForeignKey("DivisionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("Division");
                });

            modelBuilder.Entity("HrisApp.Shared.Models.Payroll.PayrollT", b =>
                {
                    b.HasOne("HrisApp.Shared.Models.Payroll.CashBondT", "Cashbond")
                        .WithMany()
                        .HasForeignKey("CashbondId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HrisApp.Shared.Models.Payroll.RateTypeT", "RateType")
                        .WithMany()
                        .HasForeignKey("RateTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HrisApp.Shared.Models.Payroll.RestDayT", "RestDay")
                        .WithMany()
                        .HasForeignKey("RestDayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HrisApp.Shared.Models.Payroll.ScheduleTypeT", "ScheduleType")
                        .WithMany()
                        .HasForeignKey("ScheduleTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cashbond");

                    b.Navigation("RateType");

                    b.Navigation("RestDay");

                    b.Navigation("ScheduleType");
                });
#pragma warning restore 612, 618
        }
    }
}
